### ISSUE TITLE
release / nightly

### ISSUE THREAD

**Issue by wrenix** [SchildiChat/schildichat-android-next#1]
a big thank you for you work.
it makes me possible to use matrix (with multiple acccounts).

Will you create your fork before element gets multiaccount xD
https://github.com/vector-im/element-meta/discussions/1832

do you have any plan to release a version (in an own fdroid or so)? And when?
or is it (only a playground for you)

**Comment by SpiritCroc** [comment]
> Will you create your fork before element gets multiaccount xD

Question unclear, this repo you're commenting on already contains a fork?

> do you have any plan to release a version (in an own fdroid or so)? And when? or is it (only a playground for you)

While it's still at playground level to some degree, I will probably put it in my [testing fdroid repo](https://s2.spiritcroc.de/testing/fdroid/repo/) soon so interested users can play with it as well.

**Comment by wrenix** [comment]
Thanky you for the information, where you want to release the first version of schildichat-next.

the rest of my message was just a big thankyou for the work till today.

**Comment by SpiritCroc** [comment]
FYI, first alpha build is in my fdroid repo (but of course don't expect too much from it)

**Comment by wrenix** [comment]
thankyou - looks good - some icon are still element (themed icon and wizzard) + i am unable to verify with other devices (did not see on init login and does not work/response on of triggerd on other devices).

thankt for working on it + i like the new icon and the faster transition

**Comment by SpiritCroc** [comment]
> some icon are still element (themed icon and wizzard)

Guess why the README says "hasn't even been entirely rebranded yet".

>  i am unable to verify with other devices (did not see on init login and does not work/response on of triggerd on other devices).

I think there may be an option in settings. But really doesn't make much sense to report things here which are most certainly upstream at this point.

> i like the new icon and the faster transition

Glad to hear!

**Comment by wrenix** [comment]
> Guess why the README says "hasn't even been entirely rebranded yet".

yes, you are correct :)

> I think there may be an option in settings. But really doesn't make much sense to report things here which are most certainly upstream at this point.

Sadly there is no option in settings of element-x/schildi-next, and that works on upstream with an inline hint, see:
https://m.youtube.com/watch?time_continue=38&v=COCMi6sAghw

---

do not feel pressured, i really like your work and every step you make is an good step.

**Comment by SpiritCroc** [comment]
> and that works on upstream with an inline hint, see: https://m.youtube.com/watch?time_continue=38&v=COCMi6sAghw thats what i am missing

That worked just fine for me on SchildiNext, and since I haven't touched anything related to that, must be something on your end.

**Comment by wrenix** [comment]
i see the new themed icon - nice work :+1:

i also test it, you are correct - it does not works just one account (same server independet from client element-x or schildiNext). So it is an upstream issue 😞
