### ISSUE TITLE
Upgrade wysisyg

### ISSUE THREAD

**Issue by austinhuang0131** [SchildiChat/schildichat-android-next#11]
**Describe the bug**
I see it is downgraded at https://github.com/SchildiChat/schildichat-android-next/commit/4935a096e20ed21b3039d7af86d5b6c12ad3a8e7. However, later version fixes a bug that I have (https://github.com/element-hq/element-x-android/issues/2439) so would you consider upgrading it or reporting any issues you have? It's https://github.com/matrix-org/matrix-rich-text-editor btw.

**Comment by SpiritCroc** [comment]
Of course, once I merge the next upstream release which bumps the wysiwyg version, I'll re-test and switch to the updated version if it's fine.

**Comment by austinhuang0131** [comment]
mostly working now
