### ISSUE TITLE
Ability to reply to push-notifications

### ISSUE THREAD

**Issue by Git-North** [SchildiChat/schildichat-android-next#15]
**Is your feature request related to a problem? Please describe.**
Feature parity with the old SchildiChat, ability to reply to push notifications 

**Describe the solution you'd like**
Element X currently does have this feature "enabled" because they haven't decided whether the "reply" button should actually reply to the message or just send one without actually replying 

**Describe alternatives you've considered**
Using the Non-X SchildiChat 

**Additional context**
Here's how both notifications look
![Screenshot_20240502_173812_Niagara Launcher](https://github.com/SchildiChat/schildichat-android-next/assets/72702125/4107155d-e5ff-4357-8bc9-6e390522ab9d)
Below is the SchildiChat-Next
![Screenshot_20240502_173711_Niagara Launcher](https://github.com/SchildiChat/schildichat-android-next/assets/72702125/3e78c3d0-553b-43f6-aedc-8c53c7d2aaea)

**Comment by Git-North** [comment]
https://github.com/element-hq/element-x-android/issues/1966#issuecomment-1843291327
https://github.com/element-hq/element-x-android/issues/185#issue-1615320385

**Comment by SpiritCroc** [comment]
I don't use this feature so I'll follow whatever Element X does

**Comment by Nelinski** [comment]
Latest version now supports this! So this can be closed
