### ISSUE TITLE
add/enable UnifiedPush support

### ISSUE THREAD

**Issue by wrenix** [SchildiChat/schildichat-android-next#2]
i have seen, that element-x has write some UnifiedPush code, but they do not build/use it.

i hope you find a way to get it running.

(sorry for the spam of issues)

**Comment by SpiritCroc** [comment]
Looks to me like [it is built](https://github.com/SchildiChat/schildichat-android-next/blob/70104ccca1e536a942ac704e9b888ef4d4ae41eb/plugins/src/main/kotlin/extension/DependencyHandleScope.kt#L92) but [not ready yet](https://github.com/vector-im/element-x-android/issues/185). Once it's ready I'll of course want to use it.

**Comment by spaetz** [comment]
Been merged as https://github.com/element-hq/element-x-android/pull/2248

It prefers Google push over UnifiedPush though, perhaps we want to switch priorities by switching out the priority indexes?

**Comment by SpiritCroc** [comment]
Don't worry, I will make sure it works fine on my setup, which uses a self-hosted NTFY and devices running MicroG.
Actually I was planning to try out to go fully FLOSS this time (no extra FCM variant), where UP handles all the push including FCM as well, if it works: https://unifiedpush.org/developers/embedded_fcm/

**Comment by SpiritCroc** [comment]
Element v0.4.2 merged.

**Comment by Akselmo** [comment]
Hi, for some reason SCX cant either find or register to NTFY on my phone. Bug or not yet done? If you need any logs just tell me what to do :)

**Comment by SpiritCroc** [comment]
> Hi, for some reason SCX cant either find or register to NTFY on my phone. Bug or not yet done? If you need any logs just tell me what to do :)

UP is supported since v0.4.2. To debug:
- Try UP-Example from fdroid to see if it works with your NTFY
- Let someone send you a matrix message which should notify your device (e.g. a message in a direct chat that is not muted)
- Check Settings/Turtle Tweaks/Push info for details on what the app knows about your push setup

**Comment by Akselmo** [comment]
1. Works, also the regular schildichat app works with ntfy
2. All other apps get the notification
3. ![Screenshot_20240218-190729](https://github.com/SchildiChat/schildichat-android-next/assets/13801236/db04cefb-93a0-4bea-b2ca-e6903c71a1a1)

I host my own homeserver, can that affect things?

**Comment by SpiritCroc** [comment]
> I host my own homeserver, can that affect things?

It *shouldn't*. Have you checked if it works on Element X >= 0.4.2?
You can also send a bug report using the inbuilt option and I can check logs if there's something striking, if I find time

**Comment by Akselmo** [comment]
Seems the issue resolved itself. 

For the record, i have version 0.4.4. Only thing I did was just wait long enough and it just started working out of the blue.
