### ISSUE TITLE
Simplified Sliding Sync Support

### ISSUE THREAD

**Issue by wkelton** [SchildiChat/schildichat-android-next#24]
When I try to use my homeserver (synapse 1.115.0 with simplified sliding sync) as the account provider with schildi next 0.6.0.SC9 installed from f-droid repo, I get an error popup - "The server currently doesn't support sliding sync".

I am able to use my homeserver with element x 0.6.3 (I have not tested with 0.6.0).

Is this expected to work now, or is a newer base element x needed?

**Smartphone (please complete the following information):**
 - Device: Samsung 22
 - OS: Android 14

**Comment by SpiritCroc** [comment]
You may want to try with the 0.6.3 build from the testing repo, or wait until 0.6.3 goes to my main fdroid repo, I think Element had a bug with that

**Comment by wkelton** [comment]
Confirmed working with 0.6.3.SC10-TEST1.

Thanks!
