### ISSUE TITLE
Activated Simplified Sliding Sync means no Sort by favorites :(

### ISSUE THREAD

**Issue by mr8tom** [SchildiChat/schildichat-android-next#25]
**Describe the bug**
When I activate Simplified Sliding Sync in Developer Options on Version 0.6.0sc8 or at 0.6.4.sc10-test4, the Option "Pin Favorites" don't work.
Same with the low priority to bottom.
When I turn SSS off, the sort order will be like exptected, again.

**Comment by SpiritCroc** [comment]
That sounds like a synapse bug

**Comment by mr8tom** [comment]
I restarted the matrix server, the issue seems to be gone :)
(still confused, is not my first restart in the last days)

**Comment by SpiritCroc** [comment]
I've heard synapse 1.116.0 fixed this :)
