### ISSUE TITLE
Space navigation bar disappears when selecting a space with no rooms

### ISSUE THREAD

**Issue by MisguidedEmails** [SchildiChat/schildichat-android-next#28]
**Describe the bug**
When selecting a space that has no rooms, the space selector disappears. Disabling and re-enabling space navigation does not bring back the selector (as it's still selected on the empty space). Effectively locking the user out of using space navigation.

**To Reproduce**
1. Enable space navigation
2. (if needed) Create a new space, with no rooms in it
3. Select the empty space in the space navigation
4. Should see the empty space screen, but no space navigation bar.

**Expected behavior**
Space navigation bar remains.

**Screenshots**
![screenshot](https://github.com/user-attachments/assets/a39782b5-65f8-4e9e-aaa6-8ed7ce7f83be)

**Smartphone (please complete the following information):**
 - Occurs on multiple different devices

**Additional context**
 - App version: 0.6.5.sc12-test2 (8722)
 - Store: SpiritCroc's F-Droid
 - Homeserver: My own.
 - Related experimental/labs settings: Confirmed this occurs on a fresh install with only space navigation enabled
 - Logs have been submitted using the app's built-in bug report (/"rageshake") mechanism: yes

**Upstream relevance**
 - Does this issue exist in Element X Android? - N/A

**Comment by SpiritCroc** [comment]
@MisguidedEmails thanks for the detailed report! Let me know if it's fixed for you on -test3

**Comment by MisguidedEmails** [comment]
@SpiritCroc yup! all good now :tada:
