### ISSUE TITLE
Infinite "configuring your account" on LineageOS phone without Google stuff

### ISSUE THREAD

**Issue by esp13** [SchildiChat/schildichat-android-next#3]
Hi,

### Unable to finalize connection to synapse home-server with slindingsync enabled:

Once the custom home-server address configured, the credentials entered, Schildichat next display a "configuring your account" display with a rotating wheel.
But this will never go further.
After some testing with other users on Sliding Sync matrix Discussion it appears that this is related to the client phone running android 13 LineageOs without all the Google stuff.

Why does Schildichat Next (Or Element X) needs some google stuff? Could we do without?

**Comment by SpiritCroc** [comment]
Once EleX has the fdroid flavor ready, Schildi will use it, which should be soon I think. My google-less AICP has no problems with running SchildiNext without Google. While I haven't tested without MicroG, this sounds more like a sliding-sync-proxy issue to me. But I won't spend time debugging upstream issues that don't affect me.

**Comment by esp13** [comment]
Thank you for your answer.
I tested this with element web and successfully connected to my homeserver with the experimental feature sliding sync activated.

An other person with a similar phone configuration (Lineage OS, afwall, no google stuff) had the same problem (endless configurating your account) with elementX, while some people from sliding syncv3 had successfully connected to his homeserver from regular phone and succeed.

So I'm not sure comes from the sliding-sync-proxy.
