### ISSUE TITLE
Names of spaces and rooms are missing

### ISSUE THREAD

**Issue by buzz** [SchildiChat/schildichat-android-next#33]
**Describe the bug**

***Spaces***

All spaces are named "Nameless space".

***Rooms***

Most rooms show "No room name". Room names do show after entering the room once. Although, after one day or so the rooms go back to showing "No room name".

**To Reproduce**
1. Install and open app
2. Login to account
3. Ensure "Space navigation" in settings is enabled
4. Look at "All chats" tab or any space tab

**Expected behavior**
I expect the app to display the actual room and space names.

**Screenshots**
<details><summary>All chats tab</summary>

![all chats](https://github.com/user-attachments/assets/e24c926a-7ab7-4d40-9666-2956b4110de4)
</details>

<details><summary>Space tab</summary>

![space tab](https://github.com/user-attachments/assets/b290a658-c8c0-499b-8da9-ed2e42524e34)
</details>

**Smartphone:**
 - Device: OnePlus Nord
 - OS: Android 13

**Additional context**
 - App version: 0.7.3.sc15 (9102) HEAD (e37d89bc)
 - Store: SpiritCroc's F-Droid
 - Homeserver: Synapse v1.119.0 (latest version as of time of writing)
 - Related experimental/labs settings: None, I tested with fresh app install and all settings to default.
 - Logs have been submitted using the app's built-in bug report (/"rageshake") mechanism: no

**Logs**
[logs.2024-11-21-15.log](https://github.com/user-attachments/files/17849140/logs.2024-11-21-15.log)

**Upstream relevance**
 - Does this issue exist in Element X Android?  
    **No, room names display fine in Element X. Spaces are not supported by Element X.**

**Notes**

- The homeserver is used with a bunch of different clients, such as Element (Android), Element (Desktop), Element X (Android), nheko, NeoChat. All other clients display room and spaces names just fine.
- All icons (room and space icons) work as expected.

**Comment by SpiritCroc** [comment]
Does your server provide a sliding-sync-proxy which you may be using instead of synapse's native simplified sync implementation? Can you try in the app's settings under Developer options the "Clear cache" option, if room names come through with that?

**Comment by SpiritCroc** [comment]
Actually I can reproduce on fresh login right now

**Comment by buzz** [comment]
> Does your server provide a sliding-sync-proxy which you may be using instead of synapse's native simplified sync implementation?

No sliding sync proxy. Only Synapse native simplified sync.

> Can you try in the app's settings under Developer options the "Clear cache" option, if room names come through with that?

After clearing the cache, all the names seem to work even the space names. I don't know yet if room names are going back to "No room name" after a day like last time though.

**Comment by SpiritCroc** [comment]
I wasn't able to reproduce on the latest v0.7.4.sc16-test3 build, maybe the upstream merge fixed it? Let me know when you get a chance to test a >= v0.7.4 build if it's better for you

**Comment by buzz** [comment]
> After clearing the cache, all the names seem to work even the space names. I don't know yet if room names are going back to "No room name" after a day like last time though.

Using the app for a week now. Since clearing the cache everything behaves normal now. 🤷

**Comment by SpiritCroc** [comment]
ok. I think it's fixed with 0.7.4, feel free to re-open if not.
