### ISSUE TITLE
Unread filter seemingly flag not respected

### ISSUE THREAD

**Issue by niebloomj** [SchildiChat/schildichat-android-next#7]
**Describe the bug**
I have the chat filter header showing and whether or not I select unread only chats, it's showing me unread first. 

**To Reproduce**
Quick settings
Add chat filter header
Click unread
Click unread again
Still only seeing unreads

**Expected behavior**
I would think the unread button works like the favorite button. When I click filter by favorites it shows up at the top, and when I deselect it the favorites go down to be sorted by time. I would think unreads should work similarly. 

**Smartphone (please complete the following information):**
Pixel 6Pro on Android 14

**Additional context**
 - App version: [Look it up in Settings / Help & About. Click "Version" there to copy it. "Latest version" is not a valid version!]
 - Store: SpiritCroc's F-Droid
 - Related experimental/labs settings: [Have you enabled any experimental or labs settings (which ones), and does the issue still exist when disabling these?]
 - Logs have been submitted using the app's built-in bug report (/"rageshake") mechanism: [yes/no]

**Upstream relevance**
 - Does this issue exist in Element X Android?
 - If this issue exists in Element X Android, please also link the corresponding bug report (create a new one if it doesn't exist yet)

**Comment by SpiritCroc** [comment]
A filter is something else than a sort order.. There is currently no setting to not order by unread.

**Comment by niebloomj** [comment]
I had a feeling that was the case. Thanks 👍

**Comment by SpiritCroc** [comment]
FWIW, the "chat list filters" were added by Element and I don't like their UX at all so far, so likely I won't touch these.
Settings to change the sort order are likely something worth considering (may be worth a separate issue), even though sliding sync makes these a bit more complicated, if we do not want to experience too many empty room previews.
