### ISSUE TITLE
Dedicated pages for DMs and rooms not in spaces

### ISSUE THREAD

**Issue by baduhai** [SchildiChat/schildichat-android-next#9]
Just creating the feature request here, since legacy SchildiChat is not getting features any more.

I wish I had an option to have pages for DMs and rooms not in spaces like on the desktop version. Here's a mockup I made:

![image](https://github.com/SchildiChat/schildichat-android-next/assets/31864305/8b73bf2f-ea20-48da-8471-d2b5c880a7d7)

Notice the bottom bar.

**Comment by SpiritCroc** [comment]
Wondering if the DMs page should filter for DMs added to spaces or show all, what would people prefer? (Note I will not add Element's auto-add-DMs-to-space-because-you're-in-the-same-space-with-that-person, this only affects DM rooms added to a space manually)

**Comment by baduhai** [comment]
I did not know you could add DMs to spaces. I would personally prefer to have _all_ DMs in place. The only reason I see for adding a DM to a space would be for puppeting bridges, but even if I were to add a DM to a space, I think I would still want to see all DMs in one place. In my mind, DMs are a separate thing to group conversations that happen in spaces.

> Note I will not add Element's auto-add-DMs-to-space-because-you're-in-the-same-space-with-that-person

I kind find this feature to be pretty annoying, and kinda useless.

**Comment by SpiritCroc** [comment]
> I did not know you could add DMs to spaces. I would personally prefer to have _all_ DMs in place. The only reason I see for adding a DM to a space would be for puppeting bridges, but even if I were to add a DM to a space, I think I would still want to see all DMs in one place. In my mind, DMs are a separate thing to group conversations that happen in spaces.

Makes sense to me :+1: 

> 
> > Note I will not add Element's auto-add-DMs-to-space-because-you're-in-the-same-space-with-that-person
> 
> I kind find this feature to be pretty annoying, and kinda useless.

I totally agree
